"""Init

Revision ID: b13a5d5e7bb7
Revises: 
Create Date: 2024-02-11 22:55:29.685094

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b13a5d5e7bb7'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bells',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('number', sa.Enum('1', '2', '3', '4', '5', '6', '7', '8', '9', name='number_of_bell_enum'), nullable=False),
    sa.Column('start_at', sa.Time(), nullable=False),
    sa.Column('end_at', sa.Time(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('number')
    )
    op.create_table('classrooms',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=20), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('type', sa.Enum('lecture', 'practice', name='classroom_type_enum'), nullable=False),
    sa.Column('deleted_at', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('groups',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=10), nullable=False),
    sa.Column('year_start', sa.SmallInteger(), nullable=False),
    sa.Column('year_end', sa.SmallInteger(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('subjects',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('teachers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(length=20), nullable=False),
    sa.Column('second_name', sa.String(length=20), nullable=True),
    sa.Column('last_name', sa.String(length=20), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('group_m2m_subject',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('group_id', sa.Integer(), nullable=True),
    sa.Column('subject_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['group_id'], ['groups.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['subject_id'], ['subjects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('lessons',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('day', sa.Enum('1', '2', '3', '4', '5', '6', name='lesson_day_enum'), nullable=False),
    sa.Column('week', sa.Enum('upper', 'lower', name='lesson_week_enum'), nullable=False),
    sa.Column('semester', sa.Enum('1', '2', name='lesson_semester_enum'), nullable=False),
    sa.Column('year', sa.SmallInteger(), nullable=False),
    sa.Column('teacher_id', sa.Integer(), nullable=False),
    sa.Column('classroom_id', sa.Integer(), nullable=False),
    sa.Column('group_id', sa.Integer(), nullable=False),
    sa.Column('subject_id', sa.Integer(), nullable=False),
    sa.Column('bell_id', sa.Integer(), nullable=False),
    sa.Column('type', sa.Enum('lecture', 'practice', name='lesson_type_enum'), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['bell_id'], ['bells.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['classroom_id'], ['classrooms.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['group_id'], ['groups.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['subject_id'], ['subjects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['teacher_id'], ['teachers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('bell_id', 'day', 'week', 'semester', 'year', 'classroom_id'),
    sa.UniqueConstraint('bell_id', 'day', 'week', 'semester', 'year', 'group_id'),
    sa.UniqueConstraint('bell_id', 'day', 'week', 'semester', 'year', 'teacher_id')
    )
    op.create_table('teacher_m2m_subject',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('teacher_id', sa.Integer(), nullable=True),
    sa.Column('subject_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['subject_id'], ['subjects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['teacher_id'], ['teachers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('teacher_m2m_subject')
    op.drop_table('lessons')
    op.drop_table('group_m2m_subject')
    op.drop_table('teachers')
    op.drop_table('subjects')
    op.drop_table('groups')
    op.drop_table('classrooms')
    op.drop_table('bells')
    # ### end Alembic commands ###
